# Generated by Django 5.2.5 on 2025-10-20 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="客户编码"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="客户名称"),
                ),
                (
                    "customer_type",
                    models.IntegerField(
                        choices=[(1, "企业"), (2, "个人")],
                        default=1,
                        verbose_name="客户类型",
                    ),
                ),
                (
                    "customer_level",
                    models.IntegerField(
                        choices=[(1, "重要"), (2, "普通"), (3, "一般")],
                        default=2,
                        verbose_name="客户等级",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="所属行业"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="联系邮箱"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="详细地址"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="信用额度",
                    ),
                ),
                (
                    "credit_days",
                    models.IntegerField(default=0, verbose_name="账期天数"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "正常"), (0, "停用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "db_table": "foundation_customer",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer_code"], name="foundation__custome_6d69ff_idx"
                    ),
                    models.Index(
                        fields=["customer_name"], name="foundation__custome_28425c_idx"
                    ),
                ],
            },
        ),
    ]
