# Generated by Django 5.2.5 on 2025-10-20 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0002_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="供应商编码"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(max_length=200, verbose_name="供应商名称"),
                ),
                (
                    "supplier_type",
                    models.IntegerField(
                        choices=[(1, "生产商"), (2, "经销商"), (3, "代理商")],
                        default=1,
                        verbose_name="供应商类型",
                    ),
                ),
                (
                    "supplier_level",
                    models.IntegerField(
                        choices=[(1, "A级"), (2, "B级"), (3, "C级")],
                        default=2,
                        verbose_name="供应商等级",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="联系邮箱"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="详细地址"
                    ),
                ),
                (
                    "payment_days",
                    models.IntegerField(default=0, verbose_name="付款账期"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "正常"), (0, "停用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_suppliers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_suppliers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
                "db_table": "foundation_supplier",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplier_code"], name="foundation__supplie_e51c2d_idx"
                    ),
                    models.Index(
                        fields=["supplier_name"], name="foundation__supplie_5e0420_idx"
                    ),
                ],
            },
        ),
    ]
