# Generated by Django 5.2.5 on 2025-10-20 08:25

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类编码"
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=100, verbose_name="分类名称"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="显示顺序")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "正常"), (0, "停用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_material_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="inventory.materialcategory",
                        verbose_name="上级分类",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_material_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料分类",
                "verbose_name_plural": "物料分类",
                "db_table": "foundation_material_category",
                "ordering": ["sort_order", "category_code"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="物料编码"
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=200, verbose_name="物料名称"),
                ),
                (
                    "material_spec",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="物料规格"
                    ),
                ),
                (
                    "material_type",
                    models.IntegerField(
                        choices=[(1, "原材料"), (2, "半成品"), (3, "成品")],
                        default=1,
                        verbose_name="物料类型",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="基本单位"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="参考价格",
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="最小库存",
                    ),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="最大库存",
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="安全库存",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=100, verbose_name="条形码"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "正常"), (0, "停用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="inventory.materialcategory",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料",
                "verbose_name_plural": "物料",
                "db_table": "foundation_material",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="仓库编码"
                    ),
                ),
                (
                    "warehouse_name",
                    models.CharField(max_length=200, verbose_name="仓库名称"),
                ),
                (
                    "warehouse_type",
                    models.IntegerField(
                        choices=[
                            (1, "原材料仓"),
                            (2, "半成品仓"),
                            (3, "成品仓"),
                            (4, "综合仓"),
                        ],
                        default=4,
                        verbose_name="仓库类型",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="仓库位置"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "正常"), (0, "停用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="仓库管理员",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库",
                "verbose_name_plural": "仓库",
                "db_table": "foundation_warehouse",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="materialcategory",
            index=models.Index(
                fields=["category_code"], name="foundation__categor_b2cc83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialcategory",
            index=models.Index(
                fields=["tree_id", "lft"], name="inventory_materialcategory4cb6"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["material_code"], name="foundation__materia_41990b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["material_name"], name="foundation__materia_105bd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["barcode"], name="foundation__barcode_f619be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["warehouse_code"], name="foundation__warehou_db0bb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["warehouse_name"], name="foundation__warehou_0dd053_idx"
            ),
        ),
    ]
